campaign: In the desolate Fey Wastes, desert tribe members embark on a quest to rescue
  a kidnapped brother after the destruction of their camp and annihilation of their
  people by a gang of Minotaurs. Joined by two amnesiac Eladrin who recently wandered
  out of the desert, the party ventures deeper into the mysteries of this barren land.
dm_objectives:
- HIDDEN LONG TERM discover the truth about what happened to the Fey Wild
- HIDDEN LONG TERM discover the truth about what happened to the Seelie Court
- SHORT TERM find their brother, Bero, who is currently held captive in a secret area
  of Hanta's compound
- SHORT TERM prevent the Marquis from discovering the truth about Bero
party: chulthanhos
players:
- class: Druid
  description: A bedouin from the deserts of the Fey Wastes who is intent on helping
    his brother that may actually be the reincarnation of Oberon; Has traveled over
    much of the Fey Wastes; Spore Druid
  name: Haemon
  secrets: None
- class: Barbarian
  description: A bedouin from the deserts of the Fey Wastes who is intent on helping
    his brother that may actually be the reincarnation of Oberon
  name: Oggvay
  secrets: None
- class: Wizard
  description: an amnesiac Eladrin
  name: Spat
  secrets: guard from the destroyed Seelie Court
- class: Monk
  description: an amnesiac Eladrin
  name: Dev
  secrets: guard from the destroyed Seelie Court
